# Generated by Django 4.1.1 on 2022-10-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemodel',
            name='isBookmarked',
            field=models.BooleanField(default=False, verbose_name='isBookmarked'),
        ),
    ]
