# Generated by Django 4.1.1 on 2022-11-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_storeamenities_storemodel_store_amenitites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemodel',
            name='image',
            field=models.ImageField(upload_to='store_images', verbose_name='image'),
        ),
    ]
