# Generated by Django 4.1.1 on 2022-10-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_storemodel_avatar_image_storemodel_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storemodel',
            name='avatar_image',
        ),
        migrations.AddField(
            model_name='storemodel',
            name='brand_image',
            field=models.FileField(null=True, upload_to='avatar_image', verbose_name='brand_image'),
        ),
    ]
