# Generated by Django 4.1.1 on 2022-11-13 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_storemodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storemodel',
            name='brand_image',
        ),
    ]
