# Generated by Django 4.1.1 on 2022-10-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_storemodel_avatar_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemodel',
            name='address',
            field=models.CharField(max_length=400, null=True, verbose_name='address'),
        ),
    ]
