# Generated by Django 4.1.1 on 2022-11-13 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_storemodel_brand_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storemodel',
            name='creator',
        ),
    ]
