# Generated by Django 4.1.1 on 2022-11-15 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_storemodel_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storemodel',
            name='creator',
        ),
    ]
