# Generated by Django 4.1.1 on 2022-10-25 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_storemodel_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storemodel',
            options={'ordering': ['-id'], 'verbose_name': 'Обустройствo дома', 'verbose_name_plural': 'Обустройствo дома'},
        ),
    ]
