# Generated by Django 4.1.1 on 2022-11-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_storemodel_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemodel',
            name='brand_image',
            field=models.ImageField(null=True, upload_to='avatar_image', verbose_name='brand_image'),
        ),
        migrations.AddField(
            model_name='storemodel',
            name='image',
            field=models.ImageField(null=True, upload_to='store_images', verbose_name='image'),
        ),
    ]
