# Generated by Django 3.2.16 on 2022-12-06 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0071_housemodel_image'),
        ('store', '0012_storemodel_brand_image_storemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemodel',
            name='price_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_price_type', to='products.pricelistmodel'),
        ),
    ]
