# Generated by Django 3.2.16 on 2022-12-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_storemodel_price_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemodel',
            name='product_status',
            field=models.CharField(choices=[('InProgress', 'InProgress'), ('PUBLISH', 'PUBLISH'), ('DELETED', 'DELETED'), ('ARCHIVED', 'ARCHIVED'), ('REJECTED', 'REJECTED')], default='InProgress', max_length=90, null=True),
        ),
    ]
